apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: nova
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: nova
spec:
  selector:
    app: backend
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  type: ClusterIP
