{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-servicemonitor" (include "nova.fullname" .) }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nova.labels" . | nindent 4 }}
    {{- toYaml .Values.metrics.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: {{ toYaml .Values.metrics.serviceMonitor.components | nindent 10 }}
  endpoints:
    - port: http
      interval: {{ .Values.metrics.interval | default "30s" }}
      path: {{ .Values.metrics.path | default "/api/metrics" }}
      scrapeTimeout: {{ .Values.metrics.scrapeTimeout | default "10s" }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
{{- end }}