apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nova-backend-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - nova
  selector:
    matchLabels:
      app.kubernetes.io/component: backend # <-- Updated to match your Helm labels
  endpoints:
    - port: http 
      path: /api/metrics
      interval: 15s
