apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nova

resources:
  - namespace.yaml
  - configmap.yaml
  - external-secret.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress.yaml

images:
  - name: nova-frontend
    newTag: latest
  - name: nova-backend
    newTag: latest